In [1]:
%matplotlib inline

In [2]:
from __future__ import print_function

In [3]:
import torch

In [4]:
x = torch.empty(5,3)
x

tensor([[9.6428e-39, 1.1112e-38, 9.5511e-39],
        [1.0102e-38, 1.0286e-38, 1.0194e-38],
        [9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38],
        [9.5510e-39, 1.0561e-38, 1.0194e-38]])

In [5]:
x =  torch.rand(5, 3)
x

tensor([[0.9487, 0.4556, 0.9975],
        [0.2421, 0.0026, 0.9861],
        [0.2792, 0.3549, 0.3967],
        [0.4404, 0.8609, 0.5306],
        [0.7409, 0.3928, 0.8325]])

In [6]:
torch.cuda.is_available()

False

In [7]:
x = torch.ones(2,2, requires_grad = True)

In [8]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [10]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [11]:
z = y * y * 3
out = z.mean()

In [12]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [13]:
out.grad_fn

In [14]:
a = torch.randn(2, 2)
a

tensor([[ 0.0515,  1.6772],
        [-0.9025, -1.0363]])

In [15]:
a = ((a * 3) / (a - 1))
a

tensor([[-0.1627,  7.4300],
        [ 1.4231,  1.5267]])

In [16]:
a.requires_grad_(True)
b = (a * a).sum()
b

tensor(59.5871, grad_fn=<SumBackward0>)

In [38]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2

y

tensor([  377.8134, -1100.0889,   363.8390], grad_fn=<MulBackward0>)